### PR TITLE
raven b+++ 1.5?

### PR DESCRIPTION
**Pull request by zSynx94**

### CODE REVIEW

**Comment by Cosmic-SC** [comment]
90% sure this is skidded

proof:
image

**Comment by StephenIsTaken** [comment]
> 

it gives 4567890 errors too

**Comment by Cosmic-SC** [comment]
> > 
> 
> it gives 4567890 errors too

💀

**Comment by zSynx94** [comment]
https://claude.ai/
This shit can skid? huh?

**Comment by zSynx94** [comment]
> > 
> 
> it gives 4567890 errors too

Oh yeah, i know 💀

**Comment by Cosmic-SC** [comment]
> https://claude.ai/ This shit can skid? huh?

that ai didnt skid YOU did...

**Comment by zSynx94** [comment]
> > https://claude.ai/ This shit can skid? huh?
> 
> that ai didnt skid YOU did...

ok '-'

**Comment by Cosmic-SC** [comment]
@StephenIsTaken close this its useless

**Pull request closed without merging**
